-- Autogenerated lua file by the Spyface tool
-- 'Wimps and posers -- leave the hall! -- ManOwaR
--
-- DO NOT HAND EDIT.
--
local tiles =
{
    {
        x = 5,
        y = 6,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
        impass = 1,
        cover = 1,
    },
    {
        x = 5,
        y = 7,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 5,
        y = 8,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 5,
        y = 9,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 5,
        y = 10,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 5,
        y = 11,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 5,
        y = 12,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 6,
        y = 6,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 6,
        y = 7,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 6,
        y = 8,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 6,
        y = 9,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 6,
        y = 10,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 6,
        y = 11,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 6,
        y = 12,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 7,
        y = 6,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 7,
        y = 7,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 7,
        y = 8,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 7,
        y = 9,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 7,
        y = 10,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 7,
        y = 11,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 7,
        y = 12,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 8,
        y = 6,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
        impass = 1,
        cover = 1,
    },
    {
        x = 8,
        y = 7,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 8,
        y = 8,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 8,
        y = 9,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 8,
        y = 10,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 8,
        y = 11,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 8,
        y = 12,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 9,
        y = 6,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 9,
        y = 7,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 9,
        y = 8,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
        impass = 1,
        cover = 1,
    },
    {
        x = 9,
        y = 9,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
        impass = 1,
        cover = 1,
    },
    {
        x = 9,
        y = 10,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 9,
        y = 11,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
        impass = 1,
        cover = 1,
    },
    {
        x = 9,
        y = 12,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 10,
        y = 6,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
        impass = 1,
        cover = 1,
    },
    {
        x = 10,
        y = 7,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 10,
        y = 8,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
        impass = 1,
        cover = 1,
    },
    {
        x = 10,
        y = 9,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
        impass = 1,
        cover = 1,
    },
    {
        x = 10,
        y = 10,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 10,
        y = 11,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
        impass = 1,
        cover = 1,
    },
    {
        x = 10,
        y = 12,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 11,
        y = 6,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 11,
        y = 7,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 11,
        y = 8,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 11,
        y = 9,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 11,
        y = 10,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 11,
        y = 11,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
        impass = 1,
        cover = 1,
    },
    {
        x = 11,
        y = 12,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 12,
        y = 6,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 12,
        y = 7,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 12,
        y = 8,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 12,
        y = 9,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
        impass = 1,
        cover = 1,
    },
    {
        x = 12,
        y = 10,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
        impass = 1,
        cover = 1,
    },
    {
        x = 12,
        y = 11,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
        impass = 1,
        cover = 1,
    },
    {
        x = 12,
        y = 12,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 13,
        y = 6,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 13,
        y = 7,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
        impass = 1,
        cover = 1,
    },
    {
        x = 13,
        y = 8,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 13,
        y = 9,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 13,
        y = 10,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 13,
        y = 11,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 13,
        y = 12,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
        impass = 1,
        cover = 1,
    },
    {
        x = 4,
        y = 8,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
        impass = 1,
        cover = 1,
    },
    {
        x = 3,
        y = 8,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
        impass = 1,
        cover = 1,
    },
    {
        x = 2,
        y = 8,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
        impass = 1,
        cover = 1,
    },
    {
        x = 4,
        y = 12,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
        impass = 1,
        cover = 1,
    },
    {
        x = 3,
        y = 12,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 2,
        y = 12,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 1,
        y = 12,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 1,
        y = 9,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 1,
        y = 10,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 1,
        y = 11,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 2,
        y = 11,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
        impass = 1,
        cover = 1,
    },
    {
        x = 3,
        y = 11,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 4,
        y = 11,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 4,
        y = 10,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 4,
        y = 9,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
        impass = 1,
        cover = 1,
    },
    {
        x = 3,
        y = 9,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 2,
        y = 9,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 2,
        y = 10,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
        impass = 1,
        cover = 1,
    },
    {
        x = 3,
        y = 10,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 13,
        y = 5,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
        impass = 1,
        cover = 1,
    },
    {
        x = 12,
        y = 5,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 11,
        y = 5,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 10,
        y = 5,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
        impass = 1,
        cover = 1,
    },
    {
        x = 9,
        y = 5,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 9,
        y = 4,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 10,
        y = 4,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
        impass = 1,
        cover = 1,
    },
    {
        x = 11,
        y = 4,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 12,
        y = 4,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 13,
        y = 4,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
        impass = 1,
        cover = 1,
    },
    {
        x = 13,
        y = 3,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 12,
        y = 3,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 11,
        y = 3,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 10,
        y = 3,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 9,
        y = 3,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 6,
        y = 3,
        zone = [[vault]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 7,
        y = 3,
        zone = [[vault]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 8,
        y = 3,
        zone = [[vault]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 6,
        y = 4,
        zone = [[vault]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 7,
        y = 4,
        zone = [[vault]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 8,
        y = 4,
        zone = [[vault]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 6,
        y = 5,
        zone = [[vault]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 7,
        y = 5,
        zone = [[vault]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 8,
        y = 5,
        zone = [[vault]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 5,
        y = 3,
        zone = [[vault]],
        variant = 0,
        tags =
        {
            "noguard",
            "bountyhunt_office",
            "saferoom_unlock",
        },
    },
    {
        x = 5,
        y = 4,
        zone = [[vault]],
        variant = 0,
        tags =
        {
            "noguard",
            "bountyhunt_office",
            "saferoom_unlock",
            "saferoom_door",
            "saferoom_doorouter",
        },
    },
    {
        x = 5,
        y = 5,
        zone = [[vault]],
        variant = 0,
        tags =
        {
            "noguard",
            "bountyhunt_office",
            "saferoom_unlock",
        },
    },
    {
        x = 4,
        y = 1,
        zone = [[vault]],
        variant = 1,
        tags =
        {
            "noguard",
            "saferoom",
        },
        impass = 1,
        cover = 1,
        sightblock = 1,
    },
    {
        x = 4,
        y = 2,
        zone = [[vault]],
        variant = 1,
        tags =
        {
            "noguard",
            "saferoom",
        },
        dynamic_impass = 1,
    },
    {
        x = 4,
        y = 3,
        zone = [[vault]],
        variant = 1,
        tags =
        {
            "noguard",
            "saferoom",
            "saferoom_unlock",
        },
    },
    {
        x = 4,
        y = 4,
        zone = [[vault]],
        variant = 1,
        tags =
        {
            "noguard",
            "saferoom",
            "saferoom_unlock",
            "saferoom_door",
        },
    },
    {
        x = 4,
        y = 5,
        zone = [[vault]],
        variant = 1,
        tags =
        {
            "noguard",
            "saferoom",
            "saferoom_unlock",
        },
        impass = 1,
        cover = 1,
    },
    {
        x = 2,
        y = 1,
        zone = [[vault]],
        variant = 1,
        tags =
        {
            "noguard",
            "saferoom",
        },
        impass = 1,
        cover = 1,
        sightblock = 1,
    },
    {
        x = 3,
        y = 1,
        zone = [[vault]],
        variant = 1,
        tags =
        {
            "noguard",
            "saferoom",
        },
        impass = 1,
        cover = 1,
    },
    {
        x = 2,
        y = 2,
        zone = [[vault]],
        variant = 2,
        tags =
        {
            "noguard",
            "saferoom",
        },
    },
    {
        x = 3,
        y = 2,
        zone = [[vault]],
        variant = 2,
        tags =
        {
            "noguard",
            "saferoom",
            "saferoom_flee",
        },
    },
    {
        x = 2,
        y = 3,
        zone = [[vault]],
        variant = 2,
        tags =
        {
            "noguard",
            "saferoom",
        },
    },
    {
        x = 3,
        y = 3,
        zone = [[vault]],
        variant = 2,
        tags =
        {
            "noguard",
            "saferoom",
        },
    },
    {
        x = 2,
        y = 4,
        zone = [[vault]],
        variant = 2,
        tags =
        {
            "noguard",
            "saferoom",
        },
    },
    {
        x = 3,
        y = 4,
        zone = [[vault]],
        variant = 2,
        tags =
        {
            "noguard",
            "saferoom",
        },
    },
    {
        x = 2,
        y = 5,
        zone = [[vault]],
        variant = 2,
        tags =
        {
            "noguard",
            "saferoom",
        },
    },
    {
        x = 3,
        y = 5,
        zone = [[vault]],
        variant = 2,
        tags =
        {
            "noguard",
            "saferoom",
        },
    },
    {
        x = 2,
        y = 6,
        zone = [[vault]],
        variant = 2,
        tags =
        {
            "noguard",
            "saferoom",
        },
    },
    {
        x = 3,
        y = 6,
        zone = [[vault]],
        variant = 2,
        tags =
        {
            "noguard",
            "saferoom",
        },
    },
    {
        x = 2,
        y = 7,
        zone = [[vault]],
        variant = 1,
        tags =
        {
            "noguard",
            "saferoom",
        },
        impass = 1,
        cover = 1,
    },
    {
        x = 3,
        y = 7,
        zone = [[vault]],
        variant = 1,
        tags =
        {
            "noguard",
            "saferoom",
        },
    },
    {
        x = 4,
        y = 6,
        zone = [[vault]],
        variant = 1,
        tags =
        {
            "noguard",
            "saferoom",
        },
        dynamic_impass = 1,
    },
    {
        x = 4,
        y = 7,
        zone = [[vault]],
        variant = 1,
        tags =
        {
            "noguard",
            "saferoom",
        },
        impass = 1,
        cover = 1,
    },
    {
        x = 1,
        y = 6,
        zone = [[vault]],
        variant = 1,
        tags =
        {
            "noguard",
            "saferoom",
        },
    },
    {
        x = 1,
        y = 7,
        zone = [[vault]],
        variant = 1,
        tags =
        {
            "noguard",
            "saferoom",
        },
        impass = 1,
        cover = 1,
    },
    {
        x = 1,
        y = 8,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
        impass = 1,
        cover = 1,
    },
    {
        x = 1,
        y = 5,
        zone = [[vault]],
        variant = 1,
        tags =
        {
            "noguard",
            "saferoom",
        },
        impass = 1,
        cover = 1,
    },
    {
        x = 1,
        y = 4,
        zone = [[vault]],
        variant = 1,
        tags =
        {
            "noguard",
            "saferoom",
        },
        impass = 1,
        cover = 1,
    },
    {
        x = 1,
        y = 3,
        zone = [[vault]],
        variant = 1,
        tags =
        {
            "noguard",
            "saferoom",
        },
        impass = 1,
        cover = 1,
    },
    {
        x = 1,
        y = 2,
        zone = [[vault]],
        variant = 1,
        tags =
        {
            "noguard",
            "saferoom",
            "saferoom_hide_facing",
        },
    },
    {
        x = 1,
        y = 1,
        zone = [[vault]],
        variant = 1,
        tags =
        {
            "noguard",
            "saferoom",
            "saferoom_hide",
        },
    },
    {
        x = 1,
        y = 13,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
        impass = 1,
        cover = 1,
    },
    {
        x = 2,
        y = 13,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
        impass = 1,
        cover = 1,
    },
    {
        x = 3,
        y = 13,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
        impass = 1,
        cover = 1,
    },
    {
        x = 4,
        y = 13,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
        impass = 1,
        cover = 1,
    },
    {
        x = 5,
        y = 13,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
        impass = 1,
        cover = 1,
    },
    {
        x = 6,
        y = 13,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 7,
        y = 13,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 8,
        y = 13,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
    },
    {
        x = 9,
        y = 13,
        zone = [[ceo_office]],
        variant = 0,
        tags =
        {
            "bountyhunt_office",
        },
        impass = 1,
        cover = 1,
    },
}
local walls =
{
    {
        x = 5,
        y = 6,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 4,
        y = 6,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 14,
        y = 6,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 13,
        y = 6,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 5,
        y = 7,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 4,
        y = 7,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 14,
        y = 7,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 13,
        y = 7,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 14,
        y = 8,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 13,
        y = 8,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 14,
        y = 12,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 13,
        y = 12,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 5,
        y = 5,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 5,
        y = 6,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 6,
        y = 5,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 6,
        y = 6,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 7,
        y = 5,
        wallIndex = [[office_door]],
        dir = 2,
    },
    {
        x = 7,
        y = 6,
        wallIndex = [[office_door]],
        dir = 6,
    },
    {
        x = 8,
        y = 5,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 8,
        y = 6,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 4,
        y = 7,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 4,
        y = 8,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 3,
        y = 7,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 3,
        y = 8,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 2,
        y = 7,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 2,
        y = 8,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 1,
        y = 7,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 1,
        y = 8,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 1,
        y = 9,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 0,
        y = 9,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 1,
        y = 10,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 0,
        y = 10,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 1,
        y = 11,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 0,
        y = 11,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 14,
        y = 11,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 13,
        y = 11,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 14,
        y = 10,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 13,
        y = 10,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 14,
        y = 9,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 13,
        y = 9,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 14,
        y = 5,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 13,
        y = 5,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 14,
        y = 4,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 13,
        y = 4,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 9,
        y = 4,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 8,
        y = 4,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 9,
        y = 5,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 8,
        y = 5,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 14,
        y = 3,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 13,
        y = 3,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 13,
        y = 2,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 13,
        y = 3,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 12,
        y = 2,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 12,
        y = 3,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 11,
        y = 2,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 11,
        y = 3,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 10,
        y = 2,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 10,
        y = 3,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 9,
        y = 2,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 9,
        y = 3,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 9,
        y = 3,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 8,
        y = 3,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 1,
        y = 8,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 0,
        y = 8,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 8,
        y = 2,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 8,
        y = 3,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 7,
        y = 2,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 7,
        y = 3,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 6,
        y = 2,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 6,
        y = 3,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 5,
        y = 2,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 5,
        y = 3,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 5,
        y = 3,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 4,
        y = 3,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 5,
        y = 4,
        wallIndex = [[blast_door]],
        dir = 4,
    },
    {
        x = 4,
        y = 4,
        wallIndex = [[blast_door]],
        dir = 0,
    },
    {
        x = 5,
        y = 5,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 4,
        y = 5,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 5,
        y = 2,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 4,
        y = 2,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 5,
        y = 1,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 4,
        y = 1,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 4,
        y = 0,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 4,
        y = 1,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 3,
        y = 0,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 3,
        y = 1,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 2,
        y = 0,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 2,
        y = 1,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 1,
        y = 0,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 1,
        y = 1,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 1,
        y = 1,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 0,
        y = 1,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 1,
        y = 2,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 0,
        y = 2,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 1,
        y = 3,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 0,
        y = 3,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 1,
        y = 4,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 0,
        y = 4,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 1,
        y = 5,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 0,
        y = 5,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 1,
        y = 6,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 0,
        y = 6,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 1,
        y = 7,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 0,
        y = 7,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 1,
        y = 12,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 0,
        y = 12,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 1,
        y = 13,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 0,
        y = 13,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 4,
        y = 13,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 4,
        y = 14,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 3,
        y = 13,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 3,
        y = 14,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 2,
        y = 13,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 2,
        y = 14,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 1,
        y = 13,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 1,
        y = 14,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 5,
        y = 13,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 5,
        y = 14,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 6,
        y = 13,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 6,
        y = 14,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 7,
        y = 13,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 7,
        y = 14,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 8,
        y = 13,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 8,
        y = 14,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 9,
        y = 6,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 8,
        y = 6,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 9,
        y = 6,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 9,
        y = 7,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 13,
        y = 6,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 13,
        y = 7,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 9,
        y = 13,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 9,
        y = 14,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 13,
        y = 12,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 13,
        y = 13,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 12,
        y = 12,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 12,
        y = 13,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 11,
        y = 12,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 11,
        y = 13,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 10,
        y = 12,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 10,
        y = 13,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 10,
        y = 13,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 9,
        y = 13,
        wallIndex = [[default_wall]],
        dir = 0,
    },
}
local units =
{
    ceo_target =
    {
        spawnChance = 1,
        maxCount = 1,
        {
            {
                x = 8,
                y = 7,
                template = [[MM_bounty_target]],
                unitData =
                {
                    facing = 1, traits={nopatrol=true, mm_fixnopatrolfacing = true, mm_nopatrolchange = true,},
                    tags =
                    {
                        "assassination",
                    },
                },
            },
            1,
        },
        {
            {
                x = 1,
                y = 12,
                template = [[MM_bounty_target]],
                unitData =
                {
                    facing = 7, traits={nopatrol=true, mm_fixnopatrolfacing = true, mm_nopatrolchange = true,},
                    tags =
                    {
                        "assassination",
                    },
                },
            },
            1,
        },
        {
            {
                x = 2,
                y = 9,
                template = [[MM_bounty_target]],
                unitData =
                {
                    facing = 6, traits={nopatrol=true, mm_fixnopatrolfacing = true, mm_nopatrolchange = true,},
                    tags =
                    {
                        "assassination",
                    },
                },
            },
            1,
        },
        {
            {
                x = 5,
                y = 7,
                template = [[MM_bounty_target]],
                unitData =
                {
                    facing = 1, traits={nopatrol=true, mm_fixnopatrolfacing = true, mm_nopatrolchange = true,},
                    tags =
                    {
                        "assassination",
                    },
                },
            },
            1,
        },
        {
            {
                x = 11,
                y = 10,
                template = [[MM_bounty_target]],
                unitData =
                {
                    facing = 5, traits={nopatrol=true, mm_fixnopatrolfacing = true, mm_nopatrolchange = true,},
                    tags =
                    {
                        "assassination",
                    },
                },
            },
            1,
        },
    },
    {
        maxCount = 6,
        spawnChance = 1,
        {
            {
                x = 4,
                y = 6,
                template = [[laser_generator]],
                unitData =
                {
                    facing = 2, traits = { startOn = true, powerGrid = "saferoom", powerGridName = "SAFE ROOM" },
                },
            },
            1,
        },
        {
            {
                x = 4,
                y = 2,
                template = [[lab_safe]],
                unitData =
                {
                    facing = 4,
                    tags =
                    {
                        "saferoom_safe",
                    },
                },
            },
            1,
        },
        {
            {
                x = 1,
                y = 7,
                template = [[security_camera_1x1]],
                unitData =
                {
                    facing = 7, traits = { MM_camera = true, },
                },
            },
            1,
        },
        {
            {
                x = 8,
                y = 3,
                template = [[security_camera_1x1]],
                unitData =
                {
                    facing = 3, traits = { MM_camera = true, },
                },
            },
            1,
        },
        {
            {
                x = 5,
                y = 5,
                template = [[security_laser_emitter_1x1]],
                unitData =
                {
                    facing = 6, traits = { startOn = true, powerGrid = "saferoom", powerGridName = "SAFE ROOM", lethal_laser = true },
                },
            },
            1,
        },
        {
            {
                x = 6,
                y = 5,
                template = [[security_laser_emitter_1x1]],
                unitData =
                {
                    facing = 6, traits = { startOn = true, powerGrid = "saferoom", powerGridName = "SAFE ROOM" },
                },
            },
            1,
        },
    },
    ceo_bodyguard =
    {
        spawnChance = 1,
        maxCount = 1,
        {
            {
                x = 5,
                y = 9,
                template = [[MM_bodyguard]],
                unitData =
                {
                    facing = 0, traits={mm_nopatrolchange = true,},
                    tags =
                    {
                        "bodyguard",
                    },
                },
            },
            1,
        },
        {
            {
                x = 6,
                y = 6,
                template = [[MM_bodyguard]],
                unitData =
                {
                    facing = 2, traits={mm_nopatrolchange = true,},
                    tags =
                    {
                        "bodyguard",
                    },
                },
            },
            1,
        },
        {
            {
                x = 11,
                y = 7,
                template = [[MM_bodyguard]],
                unitData =
                {
                    facing = 2, traits={mm_nopatrolchange = true,},
                    tags =
                    {
                        "bodyguard",
                    },
                },
            },
            1,
        },
    },
}
local decos =
{
    {
        x = 10,
        y = 5,
        kanim = [[decor_sk_office_desk1]],
        facing = 4,
    },
    {
        x = 12,
        y = 10,
        kanim = [[decor_sk_office_couch1]],
        facing = 4,
    },
    {
        x = 10,
        y = 11,
        kanim = [[decor_sk_office_couch1]],
        facing = 6,
    },
    {
        x = 12,
        y = 11,
        kanim = [[decor_sk_office_lamp1]],
        facing = 6,
    },
    {
        x = 9,
        y = 8,
        kanim = [[decor_sk_office_koipond1]],
        facing = 6,
    },
    {
        x = 5,
        y = 6,
        kanim = [[decor_sk_office_planter1]],
        facing = 6,
    },
    {
        x = 4,
        y = 9,
        kanim = [[decor_sk_office_planter1]],
        facing = 6,
    },
    {
        x = 3,
        y = 8,
        kanim = [[decor_sk_office_planter2]],
        facing = 6,
    },
    {
        x = 4,
        y = 8,
        kanim = [[decor_sk_office_pillar1]],
        facing = 6,
    },
    {
        x = 4,
        y = 13,
        kanim = [[decor_sk_office_pillar1]],
        facing = 6,
    },
    {
        x = 4,
        y = 12,
        kanim = [[decor_sk_office_planter2]],
        facing = 6,
    },
    {
        x = 3,
        y = 13,
        kanim = [[decor_sk_office_planter1]],
        facing = 6,
    },
    {
        x = 2,
        y = 10,
        kanim = [[decor_sk_office_ceo_desk1]],
        facing = 0,
    },
    {
        x = 13,
        y = 5,
        kanim = [[decor_sk_office_chair1]],
        facing = 4,
    },
    {
        x = 13,
        y = 4,
        kanim = [[decor_sk_office_lamp1]],
        facing = 4,
    },
    {
        x = 1,
        y = 10,
        kanim = [[decor_sk_office_wall_paintings2]],
        facing = 0,
    },
    {
        x = 1,
        y = 11,
        kanim = [[decor_sk_office_wall_paintings3]],
        facing = 0,
    },
    {
        x = 1,
        y = 9,
        kanim = [[decor_sk_office_wall_light1]],
        facing = 0,
    },
    {
        x = 1,
        y = 12,
        kanim = [[decor_sk_office_wall_light1]],
        facing = 0,
    },
    {
        x = 8,
        y = 6,
        kanim = [[decor_sk_office_podium1]],
        facing = 0,
    },
    {
        x = 10,
        y = 6,
        kanim = [[decor_sk_office_podium1]],
        facing = 0,
    },
    {
        x = 13,
        y = 6,
        kanim = [[decor_sk_office_wall_tv1]],
        facing = 6,
    },
    {
        x = 1,
        y = 13,
        kanim = [[decor_sk_office_shelf2]],
        facing = 6,
    },
    {
        x = 2,
        y = 8,
        kanim = [[decor_sk_office_shelf2]],
        facing = 2,
    },
    {
        x = 5,
        y = 13,
        kanim = [[decor_sk_office_podium1]],
        facing = 4,
    },
    {
        x = 9,
        y = 4,
        kanim = [[decor_sk_office_wall_light1]],
        facing = 0,
    },
    {
        x = 9,
        y = 5,
        kanim = [[decor_sk_office_wall_light1]],
        facing = 0,
    },
    {
        x = 13,
        y = 12,
        kanim = [[decor_sk_office_pillar1]],
        facing = 0,
    },
    {
        x = 9,
        y = 7,
        kanim = [[decor_sk_office_wall_light1]],
        facing = 2,
    },
    {
        x = 13,
        y = 7,
        kanim = [[decor_sk_office_wall_light1]],
        facing = 2,
    },
    {
        x = 13,
        y = 9,
        kanim = [[decor_sk_office_wall_light1]],
        facing = 4,
    },
    {
        x = 10,
        y = 12,
        kanim = [[decor_sk_office_wall_light1]],
        facing = 6,
    },
    {
        x = 13,
        y = 7,
        kanim = [[decor_sk_office_planter2]],
        facing = 6,
    },
    {
        x = 9,
        y = 11,
        kanim = [[decor_sk_office_podium1]],
        facing = 6,
    },
    {
        x = 9,
        y = 13,
        kanim = [[decor_sk_office_planter2]],
        facing = 6,
    },
    {
        x = 4,
        y = 5,
        kanim = [[decor_ko_lab_pillar1]],
        facing = 4,
    },
    {
        x = 4,
        y = 3,
        kanim = [[decor_sk_lab_wall_phonepanel1]],
        facing = 4,
    },
    {
        x = 1,
        y = 4,
        kanim = [[decor_ko_barracks_walldividerguns1]],
        facing = 0,
    },
    {
        x = 1,
        y = 5,
        kanim = [[decor_ko_barracks_walldivider1]],
        facing = 2,
    },
    {
        x = 1,
        y = 6,
        kanim = [[decor_ko_lab_wallbox1]],
        facing = 0,
    },
    {
        x = 4,
        y = 7,
        kanim = [[decor_ko_lab_case1]],
        facing = 6,
    },
    {
        x = 2,
        y = 7,
        kanim = [[holdingcell_2x1_bunk1]],
        facing = 2,
    },
    {
        x = 3,
        y = 7,
        kanim = [[decor_ko_barracks_walllight1]],
        facing = 6,
    },
    {
        x = 4,
        y = 4,
        kanim = [[guardoffice_1x1_floorpanel2]],
        facing = 2,
    },
    {
        x = 2,
        y = 1,
        kanim = [[decor_ko_barracks_fridge1]],
        facing = 2,
    },
    {
        x = 1,
        y = 3,
        kanim = [[decor_ko_barracks_armourlocker1]],
        facing = 0,
    },
    {
        x = 4,
        y = 1,
        kanim = [[decor_ko_lab_tallcase1]],
        facing = 6,
    },
    {
        x = 3,
        y = 1,
        kanim = [[decor_ko_lab_case1]],
        facing = 0,
    },
}
local lights =
{
}
local sounds =
{
    {
        name = [[Objects/fishpond]],
        x = 9,
        y = 8,
    },
}
local export =
{
    cgraph =
    {
        edges =
        {
            {
                id0 = 1,
                x0 = 14,
                y0 = 6,
                id1 = 100,
                x1 = 13,
                y1 = 6,
            },
            {
                id0 = 2,
                x0 = 14,
                y0 = 7,
                id1 = 100,
                x1 = 13,
                y1 = 7,
            },
            {
                id0 = 3,
                x0 = 14,
                y0 = 8,
                id1 = 100,
                x1 = 13,
                y1 = 8,
            },
            {
                id0 = 4,
                x0 = 14,
                y0 = 12,
                id1 = 100,
                x1 = 13,
                y1 = 12,
            },
            {
                id0 = 100,
                x0 = 1,
                y0 = 9,
                id1 = 5,
                x1 = 0,
                y1 = 9,
            },
            {
                id0 = 100,
                x0 = 1,
                y0 = 10,
                id1 = 6,
                x1 = 0,
                y1 = 10,
            },
            {
                id0 = 100,
                x0 = 1,
                y0 = 11,
                id1 = 7,
                x1 = 0,
                y1 = 11,
            },
            {
                id0 = 8,
                x0 = 14,
                y0 = 11,
                id1 = 100,
                x1 = 13,
                y1 = 11,
            },
            {
                id0 = 9,
                x0 = 14,
                y0 = 10,
                id1 = 100,
                x1 = 13,
                y1 = 10,
            },
            {
                id0 = 10,
                x0 = 14,
                y0 = 9,
                id1 = 100,
                x1 = 13,
                y1 = 9,
            },
            {
                id0 = 11,
                x0 = 14,
                y0 = 5,
                id1 = 100,
                x1 = 13,
                y1 = 5,
            },
            {
                id0 = 12,
                x0 = 14,
                y0 = 4,
                id1 = 100,
                x1 = 13,
                y1 = 4,
            },
            {
                id0 = 13,
                x0 = 14,
                y0 = 3,
                id1 = 100,
                x1 = 13,
                y1 = 3,
            },
            {
                id0 = 14,
                x0 = 13,
                y0 = 2,
                id1 = 100,
                x1 = 13,
                y1 = 3,
            },
            {
                id0 = 15,
                x0 = 12,
                y0 = 2,
                id1 = 100,
                x1 = 12,
                y1 = 3,
            },
            {
                id0 = 16,
                x0 = 11,
                y0 = 2,
                id1 = 100,
                x1 = 11,
                y1 = 3,
            },
            {
                id0 = 17,
                x0 = 10,
                y0 = 2,
                id1 = 100,
                x1 = 10,
                y1 = 3,
            },
            {
                id0 = 18,
                x0 = 9,
                y0 = 2,
                id1 = 100,
                x1 = 9,
                y1 = 3,
            },
            {
                id0 = 100,
                x0 = 1,
                y0 = 8,
                id1 = 19,
                x1 = 0,
                y1 = 8,
            },
            {
                id0 = 20,
                x0 = 8,
                y0 = 2,
                id1 = 100,
                x1 = 8,
                y1 = 3,
            },
            {
                id0 = 21,
                x0 = 7,
                y0 = 2,
                id1 = 100,
                x1 = 7,
                y1 = 3,
            },
            {
                id0 = 22,
                x0 = 6,
                y0 = 2,
                id1 = 100,
                x1 = 6,
                y1 = 3,
            },
            {
                id0 = 23,
                x0 = 5,
                y0 = 2,
                id1 = 100,
                x1 = 5,
                y1 = 3,
            },
            {
                id0 = 23,
                x0 = 5,
                y0 = 2,
                id1 = 100,
                x1 = 4,
                y1 = 2,
            },
            {
                id0 = 24,
                x0 = 5,
                y0 = 1,
                id1 = 100,
                x1 = 4,
                y1 = 1,
            },
            {
                id0 = 25,
                x0 = 4,
                y0 = 0,
                id1 = 100,
                x1 = 4,
                y1 = 1,
            },
            {
                id0 = 26,
                x0 = 3,
                y0 = 0,
                id1 = 100,
                x1 = 3,
                y1 = 1,
            },
            {
                id0 = 27,
                x0 = 2,
                y0 = 0,
                id1 = 100,
                x1 = 2,
                y1 = 1,
            },
            {
                id0 = 28,
                x0 = 1,
                y0 = 0,
                id1 = 100,
                x1 = 1,
                y1 = 1,
            },
            {
                id0 = 100,
                x0 = 1,
                y0 = 1,
                id1 = 29,
                x1 = 0,
                y1 = 1,
            },
            {
                id0 = 100,
                x0 = 1,
                y0 = 2,
                id1 = 30,
                x1 = 0,
                y1 = 2,
            },
            {
                id0 = 100,
                x0 = 1,
                y0 = 3,
                id1 = 31,
                x1 = 0,
                y1 = 3,
            },
            {
                id0 = 100,
                x0 = 1,
                y0 = 4,
                id1 = 32,
                x1 = 0,
                y1 = 4,
            },
            {
                id0 = 100,
                x0 = 1,
                y0 = 5,
                id1 = 33,
                x1 = 0,
                y1 = 5,
            },
            {
                id0 = 100,
                x0 = 1,
                y0 = 6,
                id1 = 34,
                x1 = 0,
                y1 = 6,
            },
            {
                id0 = 100,
                x0 = 1,
                y0 = 7,
                id1 = 35,
                x1 = 0,
                y1 = 7,
            },
            {
                id0 = 100,
                x0 = 1,
                y0 = 12,
                id1 = 36,
                x1 = 0,
                y1 = 12,
            },
            {
                id0 = 100,
                x0 = 1,
                y0 = 13,
                id1 = 37,
                x1 = 0,
                y1 = 13,
            },
            {
                id0 = 100,
                x0 = 4,
                y0 = 13,
                id1 = 38,
                x1 = 4,
                y1 = 14,
            },
            {
                id0 = 100,
                x0 = 3,
                y0 = 13,
                id1 = 39,
                x1 = 3,
                y1 = 14,
            },
            {
                id0 = 100,
                x0 = 2,
                y0 = 13,
                id1 = 40,
                x1 = 2,
                y1 = 14,
            },
            {
                id0 = 100,
                x0 = 1,
                y0 = 13,
                id1 = 41,
                x1 = 1,
                y1 = 14,
            },
            {
                id0 = 100,
                x0 = 5,
                y0 = 13,
                id1 = 42,
                x1 = 5,
                y1 = 14,
            },
            {
                id0 = 100,
                x0 = 6,
                y0 = 13,
                id1 = 43,
                x1 = 6,
                y1 = 14,
            },
            {
                id0 = 100,
                x0 = 7,
                y0 = 13,
                id1 = 44,
                x1 = 7,
                y1 = 14,
            },
            {
                id0 = 100,
                x0 = 8,
                y0 = 13,
                id1 = 45,
                x1 = 8,
                y1 = 14,
            },
            {
                id0 = 100,
                x0 = 9,
                y0 = 13,
                id1 = 46,
                x1 = 9,
                y1 = 14,
            },
            {
                id0 = 100,
                x0 = 13,
                y0 = 12,
                id1 = 47,
                x1 = 13,
                y1 = 13,
            },
            {
                id0 = 100,
                x0 = 12,
                y0 = 12,
                id1 = 48,
                x1 = 12,
                y1 = 13,
            },
            {
                id0 = 100,
                x0 = 11,
                y0 = 12,
                id1 = 49,
                x1 = 11,
                y1 = 13,
            },
            {
                id0 = 100,
                x0 = 10,
                y0 = 12,
                id1 = 50,
                x1 = 10,
                y1 = 13,
            },
            {
                id0 = 50,
                x0 = 10,
                y0 = 13,
                id1 = 100,
                x1 = 9,
                y1 = 13,
            },
            {
                id0 = 2,
                x0 = 14,
                y0 = 7,
                id1 = 100,
                x1 = 13,
                y1 = 7,
            },
            {
                id0 = 47,
                x0 = 13,
                y0 = 13,
                id1 = 100,
                x1 = 13,
                y1 = 12,
            },
            {
                id0 = 4,
                x0 = 14,
                y0 = 12,
                id1 = 100,
                x1 = 13,
                y1 = 12,
            },
            {
                id0 = 11,
                x0 = 14,
                y0 = 5,
                id1 = 100,
                x1 = 13,
                y1 = 5,
            },
            {
                id0 = 12,
                x0 = 14,
                y0 = 4,
                id1 = 100,
                x1 = 13,
                y1 = 4,
            },
            {
                id0 = 24,
                x0 = 5,
                y0 = 1,
                id1 = 100,
                x1 = 4,
                y1 = 1,
            },
            {
                id0 = 25,
                x0 = 4,
                y0 = 0,
                id1 = 100,
                x1 = 4,
                y1 = 1,
            },
            {
                id0 = 23,
                x0 = 5,
                y0 = 2,
                id1 = 100,
                x1 = 4,
                y1 = 2,
            },
            {
                id0 = 27,
                x0 = 2,
                y0 = 0,
                id1 = 100,
                x1 = 2,
                y1 = 1,
            },
            {
                id0 = 26,
                x0 = 3,
                y0 = 0,
                id1 = 100,
                x1 = 3,
                y1 = 1,
            },
            {
                id0 = 35,
                x0 = 0,
                y0 = 7,
                id1 = 100,
                x1 = 1,
                y1 = 7,
            },
            {
                id0 = 19,
                x0 = 0,
                y0 = 8,
                id1 = 100,
                x1 = 1,
                y1 = 8,
            },
            {
                id0 = 33,
                x0 = 0,
                y0 = 5,
                id1 = 100,
                x1 = 1,
                y1 = 5,
            },
            {
                id0 = 32,
                x0 = 0,
                y0 = 4,
                id1 = 100,
                x1 = 1,
                y1 = 4,
            },
            {
                id0 = 31,
                x0 = 0,
                y0 = 3,
                id1 = 100,
                x1 = 1,
                y1 = 3,
            },
            {
                id0 = 41,
                x0 = 1,
                y0 = 14,
                id1 = 100,
                x1 = 1,
                y1 = 13,
            },
            {
                id0 = 37,
                x0 = 0,
                y0 = 13,
                id1 = 100,
                x1 = 1,
                y1 = 13,
            },
            {
                id0 = 40,
                x0 = 2,
                y0 = 14,
                id1 = 100,
                x1 = 2,
                y1 = 13,
            },
            {
                id0 = 39,
                x0 = 3,
                y0 = 14,
                id1 = 100,
                x1 = 3,
                y1 = 13,
            },
            {
                id0 = 38,
                x0 = 4,
                y0 = 14,
                id1 = 100,
                x1 = 4,
                y1 = 13,
            },
            {
                id0 = 42,
                x0 = 5,
                y0 = 14,
                id1 = 100,
                x1 = 5,
                y1 = 13,
            },
            {
                id0 = 46,
                x0 = 9,
                y0 = 14,
                id1 = 100,
                x1 = 9,
                y1 = 13,
            },
            {
                id0 = 50,
                x0 = 10,
                y0 = 13,
                id1 = 100,
                x1 = 9,
                y1 = 13,
            },
        },
    },
    width = 13,
    height = 13,
    version = 1,
    tiles = tiles,
    walls = walls,
    units = units,
    decos = decos,
    lights = lights,
    sounds = sounds,
}
return export
